name: fsp-hack
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.10
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-db}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-user}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-12345}
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ../db/clickhouse/data:/var/lib/clickhouse
      - type: bind
        source: ../db/clickhouse/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    extra_hosts:
      - "host.docker.internal:host-gateway"
