api_keys:
  # - 6f15e730-0eb6-11e3-9053-af0e97bcb74e
enable_docs: true
enable_pprof: true
server:
  mode: debug
  host: 0.0.0.0
  port: 3002
  shutdown_timeout: 10
log:
  level: debug
  encoding: json # json or console
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]
  show_file_line: true
  encoder_config:
    message_key: message
    level_key: level
    level_encoder: lowercase
    time_key: timestamp
    time_encoder: iso8601
mail:
  host: smtp.mail.ru
  port: 587
  username: user
  password: pass
  subject: Zero-Cost Developers Уведомления
  body: |
    <!DOCTYPE html>
    <html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Подтверждение уведомлений</title>
    </head>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f9f9f9; margin: 0; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background: #ffffff; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
            <h2 style="color: #555;">Подтверждение уведомлений</h2>
            <p>Перейдите по ссылке в этом письме, если согласны получать уведомления об интересующих Вас мероприятиях платформы от команды <strong>Zero-Cost Developers</strong>:</p>
            <p style="text-align: center; margin: 20px 0;">
                <a href="https://localhost:5173/confirm/%s"
                   style="display: inline-block; padding: 12px 20px; color: #fff; background-color: #007bff; text-decoration: none; border-radius: 5px;">Подтвердить</a>
            </p>
            <p style="color: #777;">Если вы не запрашивали это письмо, просто проигнорируйте его.</p>
        </div>
    </body>
    </html>
database:
  clickhouse:
    name: db
    username: user
    password: 12345
    host: localhost
    port: 9001
  postgres:
    name: db
    username: user
    password: 12345
    host: postgres
    port: 5432
  opensearch:
    host: localhost
    port: 9200
    username: admin
    password: Za4emontebe
    index: events
