api_keys:
  # - 6f15e730-0eb6-11e3-9053-af0e97bcb74e
enable_docs: true
enable_pprof: true
server:
  mode: debug
  host: 0.0.0.0
  port: 3000
  shutdown_timeout: 10
log:
  level: debug
  encoding: json # json or console
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]
  show_file_line: true
  encoder_config:
    message_key: message
    level_key: level
    level_encoder: lowercase
    time_key: timestamp
    time_encoder: iso8601
mail:
  host: smtp.mail.ru
  port: 465
  username: user
  password: pass
  subject: Zero-Cost Developers Уведомления
  body: |
    Перейдите по ссылке в этом письме, если согласны получать уведомления
    об интересующих Вас мероприятиях платформы от команды Zero-Cost Developers:

    https://cc.alivetech.org/s/rick
database:
  clickhouse:
    name: db
    username: user
    password: 12345
    host: localhost
    port: 9001
  postgres:
    name: db
    username: user
    password: 12345
    host: postgres
    port: 5432
  opensearch:
    host: localhost
    port: 9200
    username: admin
    password: Za4emontebe
    index: event-index
